module.exports = function (grunt) {
	grunt.initConfig({
		jshint: {
			all: [
				"bala/0.1.9/js/bala.fixed.js",
				"bootstrap/3.3.7/js/bootstrap.fixed.js",
				"chriswrightdesign/js/ie8Events.fixed.js",
				"classlist-polyfill/d94a623c25bc69caf09f7089c0066fd65e760e82/classList.fixed.js",
				"crel/3.0.0/js/crel.fixed.js",
				"docReady/1.0.0/js/docready.fixed.js",
				"doSlide/1.1.4/js/do-slide.fixed.js",
				"es6-promise/3.2.2/js/es6-promise.fixed.js",
				"Evento/1.0.0/js/evento.fixed.js",
				"fastclick/1.0.6/js/fastclick.fixed.js",
				"fetch/1.0.0/js/fetch.fixed.js",
				"google-code-prettify/0.1/js/prettify.lang-css.fixed.js",
				"jquery/1.10.2/js/jquery.fixed.js",
				"jquery/2.2.4/js/jquery.fixed.js",
				"jquery-builder/0.7.0/dist/2.1.1/js/jquery-deprecated-wrap.fixed.js",
				"jqueryui/1.10.4/custom/js/jquery-ui.custom.fixed.js",
				"jqueryui/1.12.1/js/jquery-ui.fixed.js",
				"js-cookie/2.1.3/js/js.cookie.fixed.js",
				"kamil/0.1.1/js/examples.js",
				"kamil/0.1.1/js/kamil.fixed.js",
				"lazyload/3.2.2/js/lazyload.fixed.js",
				"loadCSS/1.2.0/js/loadCSS.fixed.js",
				"loadJS/0.2.3/js/loadJS.fixed.js",
				"location-origin.js/1.1.4/js/location-origin.fixed.js",
				"ManUp.js/0.7/js/manup.fixed.js",
				"masonry/4.1.1/js/masonry.imagesloaded.pkgd.fixed.js",
				"masonry/4.1.1/js/masonry.pkgd.fixed.js",
				"packery/2.1.1/js/packery.draggabilly.pkgd.fixed.js",
				"parallax/2.1.3/js/parallax.fixed.js",
				"paulirish/js/matchMedia.fixed.js",
				"paulirish/js/rAF.fixed.js",
				"photoswipe/4.1.0/js/photoswipe.photoswipe-ui-default.fixed.js",
				"pnotify/1.3.1/js/pnotify.fixed.js",
				"polyfill/0.1.27/js/url.fixed.js",
				"polyfills/0.1/js/dataset.fixed.js",
				"polyfills/0.1/js/Storage.fixed.js",
				"Prism/6.1.0/js/prism.fixed.js",
				"reqwest/2.0.5/js/reqwest.fixed.js",
				"routie/0.3.2/js/routie.fixed.js",
				"setImmediate/1.0.5/js/setImmediate.fixed.js",
				"shower/1.0.1/js/shower.fixed.js",
				"sw-toolbox/3.6.1/js/sw-toolbox.fixed.js",
				"tablesort/4.0.1/js/tablesort.fixed.js",
				"tether/1.3.7/js/tether.fixed.js",
				"ToProgress/0.1.1/js/ToProgress.fixed.js",
				"UItoTop-jQuery-Plugin/1.2/js/jquery.ui.totop.js",
				"weakmap-polyfill/2.0.0/js/weakmap-polyfill.fixed.js",
				"webcomponentsjs/0.7.22/MutationObserver/js/MutationObserver.fixed.js",
				"zenscroll/3.2.2/js/zenscroll.fixed.js"
			]
		}
	});
	grunt.loadNpmTasks("grunt-contrib-jshint");
	grunt.registerTask("default", "jshint");
};
